# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Execute Python Script
      run: |
        python main.py ${{ secrets.S3_ACCESS_TOKEN }} ${{ secrets.S3_SECRET_ACCESS_TOKEN }}
    - name: Send email with attachment
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: Your Regular Reminder to Stay Hydrated!
        body: file://README.md
        from: ${{ secrets.EMAIL_USERNAME }}
        to: ${{ secrets.EMAIL_USERNAME }}
        attachments: image.png

